# GDP Data Cleaning

This notebook cleans the World Bank GDP data to only include GDP values for 2021, region, and IncomeGroup variables. Following cleaning, the data is merged with the Netflix data. 
Only the countries included in both datasets are kept in the final analytic dataset.

In [1]:
import pandas as pd 
import numpy as np 
import os

In [2]:
os.chdir("/Users/steffenerickson/Desktop/repos/DS-Netflix-Project")

In [3]:
path_to_gdp = "/Users/steffenerickson/Desktop/repos/DS-Netflix-Project/gdp_data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_3628616.csv"

In [4]:
path_to_metadata = "/Users/steffenerickson/Desktop/repos/DS-Netflix-Project/gdp_data/Metadata_Country_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_3628616.csv"

In [5]:
path_to_netflix = "/Users/steffenerickson/Desktop/repos/DS-Netflix-Project/Netflix subscription fee Dec-2021.csv"

 ### Cleaning GDP Data

In [6]:
df_gdp = pd.read_csv(path_to_gdp, skiprows = 3, header = 0 , dtype = str)

In [7]:
df_gdp2 = df_gdp[['Country Code','Country Name', '2020']].copy()

In [8]:
df_gdp2 = df_gdp2.rename(columns={'2020':'2020_GDP'})
df_gdp2['2020_GDP'] = df_gdp2['2020_GDP'].apply(lambda x: float(x) if isinstance(x, str) else x)

In [9]:
df_gdp2.head()

  Country Code                 Country Name      2020_GDP
0          ABW                        Aruba           NaN
1          AFE  Africa Eastern and Southern  9.207923e+11
2          AFG                  Afghanistan  2.011614e+10
3          AFW   Africa Western and Central  7.845876e+11
4          AGO                       Angola  5.837598e+10

### Cleaning Meta Data

In [10]:
df_meta = pd.read_csv(path_to_metadata, header = 0 , dtype = str, usecols = [0,1,2])

In [11]:
df_meta.head()
len(df_meta)

265

### Merging data

In [12]:
GDP_Final = pd.merge(df_gdp2, df_meta, on="Country Code", how="right")

In [13]:
GDP_Final.head(30)

,Country Code,Country Name,2020_GDP,Region,IncomeGroup
0,ABW,Aruba,NaN,Latin America & Caribbean,High income
1,AFE,Africa Eastern and Southern,9.207923e+11,NaN,NaN
2,AFG,Afghanistan,2.011614e+10,South Asia,Low income
3,AFW,Africa Western and Central,7.845876e+11,NaN,NaN
4,AGO,Angola,5.837598e+10,Sub-Saharan Africa,Lower middle income
5,ALB,Albania,1.488763e+10,Europe & Central Asia,Upper middle income
6,AND,Andorra,NaN,Europe & Central Asia,High income
7,ARB,Arab World,2.447584e+12,NaN,NaN
8,ARE,United Arab Emirates,3.588688e+11,Middle East & North Africa,High income
9,ARG,Argentina,3.892881e+11,Latin America & Caribbean,Upper middle income
10,ARM,Armenia,1.264121e+10,Europe & Central Asia,Upper middle income
11,ASM,American Samoa,7.090000e+08,East Asia & Pacific,Upper middle income
12,ATG,Antigua and Barbuda,1.370281e+09,Latin America & Caribbean,High income
13,AUS,Australia,1.327836e+12,East Asia & Pacific,High income
14,AUT,Austria,4.332585e+11,Europe & Central Asia,High income
15,AZE,Azerbaijan,4.260718e+10,Europe & Central Asia,Upper middle income
16,BDI,Burundi,2.841786e+09,Sub-Saharan Africa,Low income
17,BEL,Belgium,5.218613e+11,Europe & Central Asia,High income
18,BEN,Benin,1.565155e+10,Sub-Saharan Africa,Lower middle income
19,BFA,Burkina Faso,1.793361e+10,Sub-Saharan Africa,Low income
20,BGD,Bangladesh,3.230570e+11,South Asia,Lower middle income
21,BGR,Bulgaria,6.988935e+10,Europe & Central Asia,Upper middle income
22,BHR,Bahrain,3.472923e+10,Middle East & North Africa,High income
23,BHS,"Bahamas, The",9.907500e+09,Latin America & Caribbean,High income
24,BIH,Bosnia and Herzegovina,1.994650e+10,Europe & Central Asia,Upper middle income
25,BLR,Belarus,6.025824e+10,Europe & Central Asia,Upper middle income
26,BLZ,Belize,1.636281e+09,Latin America & Caribbean,Lower middle income
27,BMU,Bermuda,6.842700e+09,North America,High income
28,BOL,Bolivia,3.657276e+10,Latin America & Caribbean,Lower middle income
29,BRA,Brazil,1.444733e+12,Latin America & Caribbean,Upper middle income

### Exporting GDP Data

In [14]:
GDP_Final.to_csv('gdp_data/gdp_final.csv')

### Merging with Netlflix data

In [51]:
netflix = pd.read_csv(path_to_netflix, header = 0)

In [52]:
netflix = netflix.rename(columns={'Country':'Country Name'})

In [79]:
#Change the names for a perfect match 
GDP_Final.replace({'Country Name':{'Czech Republic': 'Czechia', 'Hong Kong SAR, China': 'Hong Kong', 
                 'Russian Federation': 'Russia', 'Slovak Republic': 'Slovakia',
                 'Korea, Rep.': 'South Korea', 'Venezuela, RB': 'Venezuela'}}, value = None, inplace=True)
                            
GDP_Final.tail(50)

,Country Code,Country Name,2020_GDP,Region,IncomeGroup
215,SSD,South Sudan,NaN,Sub-Saharan Africa,Low income
216,SSF,Sub-Saharan Africa,1.705380e+12,NaN,NaN
217,SST,Small states,4.514237e+11,NaN,NaN
218,STP,Sao Tome and Principe,4.729145e+08,Sub-Saharan Africa,Lower middle income
219,SUR,Suriname,2.884248e+09,Latin America & Caribbean,Upper middle income
220,SVK,Slovakia,1.051726e+11,Europe & Central Asia,High income
221,SVN,Slovenia,5.358961e+10,Europe & Central Asia,High income
222,SWE,Sweden,5.412201e+11,Europe & Central Asia,High income
223,SWZ,Eswatini,3.972729e+09,Sub-Saharan Africa,Lower middle income
224,SXM,Sint Maarten (Dutch part),NaN,Latin America & Caribbean,High income
225,SYC,Seychelles,1.059886e+09,Sub-Saharan Africa,High income
226,SYR,Syrian Arab Republic,NaN,Middle East & North Africa,Low income
227,TCA,Turks and Caicos Islands,9.245830e+08,Latin America & Caribbean,High income
228,TCD,Chad,1.082908e+10,Sub-Saharan Africa,Low income
229,TEA,East Asia & Pacific (IDA & IBRD countries),1.742666e+13,NaN,NaN
230,TEC,Europe & Central Asia (IDA & IBRD countries),3.876733e+12,NaN,NaN
231,TGO,Togo,7.574637e+09,Sub-Saharan Africa,Low income
232,THA,Thailand,5.016437e+11,East Asia & Pacific,Upper middle income
233,TJK,Tajikistan,8.194150e+09,Europe & Central Asia,Lower middle income
234,TKM,Turkmenistan,NaN,Europe & Central Asia,Upper middle income
235,TLA,Latin America & the Caribbean (IDA & IBRD coun...,4.478206e+12,NaN,NaN
236,TLS,Timor-Leste,1.902157e+09,East Asia & Pacific,Lower middle income
237,TMN,Middle East & North Africa (IDA & IBRD countries),1.180179e+12,NaN,NaN
238,TON,Tonga,4.888300e+08,East Asia & Pacific,Upper middle income
239,TSA,South Asia (IDA & IBRD),3.386420e+12,NaN,NaN
240,TSS,Sub-Saharan Africa (IDA & IBRD countries),1.705380e+12,NaN,NaN
241,TTO,Trinidad and Tobago,2.158804e+10,Latin America & Caribbean,High income
242,TUN,Tunisia,4.162035e+10,Middle East & North Africa,Lower middle income
243,TUR,Turkey,7.199548e+11,Europe & Central Asia,Upper middle income
244,TUV,Tuvalu,4.885555e+07,East Asia & Pacific,Upper middle income
245,TZA,Tanzania,6.240971e+10,Sub-Saharan Africa,Lower middle income
246,UGA,Uganda,3.760037e+10,Sub-Saharan Africa,Low income
247,UKR,Ukraine,1.554990e+11,Europe & Central Asia,Lower middle income
248,UMC,Upper middle income,2.315067e+13,NaN,NaN
249,URY,Uruguay,5.362883e+10,Latin America & Caribbean,High income
250,USA,United States,2.095303e+13,North America,High income
251,UZB,Uzbekistan,5.992995e+10,Europe & Central Asia,Lower middle income
252,VCT,St. Vincent and the Grenadines,8.074741e+08,Latin America & Caribbean,Upper middle income
253,VEN,Venezuela,NaN,Latin America & Caribbean,NaN
254,VGB,British Virgin Islands,NaN,Latin America & Caribbean,High income
255,VIR,Virgin Islands (U.S.),NaN,Latin America & Caribbean,High income
256,VNM,Vietnam,2.711584e+11,East Asia & Pacific,Lower middle income
257,VUT,Vanuatu,8.815479e+08,East Asia & Pacific,Lower middle income
258,WLD,World,8.474698e+13,NaN,NaN
259,WSM,Samoa,8.071008e+08,East Asia & Pacific,Lower middle income
260,XKX,Kosovo,7.716925e+09,Europe & Central Asia,Upper middle income
261,YEM,"Yemen, Rep.",NaN,Middle East & North Africa,Low income
262,ZAF,South Africa,3.354421e+11,Sub-Saharan Africa,Upper middle income
263,ZMB,Zambia,1.811063e+10,Sub-Saharan Africa,Lower middle income
264,ZWE,Zimbabwe,1.805117e+10,Sub-Saharan Africa,Lower middle income

In [80]:
netflix_gdp = pd.merge(netflix, GDP_Final, on = "Country Name", how = "left")

In [81]:
netflix_gdp2 = netflix_gdp.drop(columns = 'Country Code')

In [82]:
netflix_gdp2 = netflix_gdp2.rename(columns={'Country Name':'Country'})

In [83]:
netflix_gdp2.head(20)

,Country_code,Country,Total Library Size,No. of TV Shows,No. of Movies,Cost Per Month - Basic ($),Cost Per Month - Standard ($),Cost Per Month - Premium ($),2020_GDP,Region,IncomeGroup
0,ar,Argentina,4760,3154,1606,3.74,6.30,9.26,3.892881e+11,Latin America & Caribbean,Upper middle income
1,au,Australia,6114,4050,2064,7.84,12.12,16.39,1.327836e+12,East Asia & Pacific,High income
2,at,Austria,5640,3779,1861,9.03,14.67,20.32,4.332585e+11,Europe & Central Asia,High income
3,be,Belgium,4990,3374,1616,10.16,15.24,20.32,5.218613e+11,Europe & Central Asia,High income
4,bo,Bolivia,4991,3155,1836,7.99,10.99,13.99,3.657276e+10,Latin America & Caribbean,Lower middle income
5,br,Brazil,4972,3162,1810,4.61,7.11,9.96,1.444733e+12,Latin America & Caribbean,Upper middle income
6,bg,Bulgaria,6797,4819,1978,9.03,11.29,13.54,6.988935e+10,Europe & Central Asia,Upper middle income
7,ca,Canada,6239,4311,1928,7.91,11.87,15.03,1.645423e+12,North America,High income
8,cl,Chile,4994,3156,1838,7.07,9.91,12.74,2.529400e+11,Latin America & Caribbean,High income
9,co,Colombia,4991,3156,1835,4.31,6.86,9.93,2.714376e+11,Latin America & Caribbean,Upper middle income
10,cr,Costa Rica,4988,3152,1836,8.99,12.99,15.99,6.184690e+10,Latin America & Caribbean,Upper middle income
11,hr,Croatia,2274,1675,599,9.03,11.29,13.54,5.720378e+10,Europe & Central Asia,High income
12,cz,Czechia,7325,5234,2091,8.83,11.49,14.15,2.453393e+11,Europe & Central Asia,High income
13,dk,Denmark,4558,2978,1580,12.00,15.04,19.60,3.560849e+11,Europe & Central Asia,High income
14,ec,Ecuador,4992,3155,1837,7.99,10.99,13.99,9.880801e+10,Latin America & Caribbean,Upper middle income
15,ee,Estonia,6456,4486,1970,9.03,11.29,13.54,3.065029e+10,Europe & Central Asia,High income
16,fi,Finland,4045,2638,1407,9.03,13.54,18.06,2.695948e+11,Europe & Central Asia,High income
17,fr,France,5445,3604,1841,10.16,15.24,20.32,2.630318e+12,Europe & Central Asia,High income
18,de,Germany,5668,3814,1854,9.03,14.67,20.32,3.846414e+12,Europe & Central Asia,High income
19,gi,Gibraltar,6167,4079,2088,9.03,14.67,20.32,NaN,Europe & Central Asia,High income

### Exporting Final Analystic Dataset

In [84]:
netflix_gdp2.to_csv('Netflix_GDP_Merged.csv')